---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.myshuju.top
  resources:
  - deploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.myshuju.top
  resources:
  - deploys/finalizers
  verbs:
  - update
- apiGroups:
  - apps.myshuju.top
  resources:
  - deploys/status
  verbs:
  - get
  - patch
  - update
