apiVersion: apps.myshuju.top/v1beta1
kind: Deploy
metadata:
  labels:
    app.kubernetes.io/name: deploy
    app.kubernetes.io/instance: deploy-sample
    app.kubernetes.io/part-of: devops
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: devops
  name: deploy-sample
  namespace: mall-team
spec:
  image: nginx
  replicas: 1
  port: 80
  expose:
    mode: ingress
    nodePort: 30001
    ingressDomain: test1.myshuju.top
    path: /


